server:
  port: 8083

spring:
  application:
    name: audit-service
  data:
    mongodb:
      uri: mongodb://root:rootpassword@localhost:27017/fsm_audit?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
