server:
  port: 8082

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource: 
    url: jdbc:postgresql://localhost:5433/fsm_user
    username: fsm_user
    password: fsm_password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "1"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000

api:
  security:
    token:
      secret: ${JWT_SECRET:super_secret_key_for_development_environment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
