apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  labels:
    app: audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: fsm/audit-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://root:rootpassword@mongodb-service:27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "fsm_audit"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  selector:
    app: audit-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
